export const CONTEXTS: { LOCAL_STORAGE: Record<string, string> } = {
	LOCAL_STORAGE: {
		ANON_USER: 'ANON_USER',
		ANON_USER_REFRESH: 'ANON_USER_REFRESH',
		FULL_USER: 'FULL_USER',
		FULL_USER_REFRESH: 'FULL_USER_REFRESH',
		DISPLAYED_WELCOME: 'DISPLAYED_WELCOME',
		USED_DASHBOARD: 'USED_DASHBOARD',
		IP_CHECK_DATE: 'IP_CHECK_DATE',
		IP_CHECK_RESULT: 'IP_CHECK_RESULT',

		TOKEN_EXPIRE: 'TOKEN_EXPIRE',
		SEEN_TUTORIAL: 'SEEN_TUTORIAL',
		HAS_LOGGED_IN: 'HAS_LOGGED_IN',
		HIDE_MAINTENANCE: 'HIDE_MAINTENANCE',
	},
};
